### ISSUE TITLE
Docker is halted after boot, seemingly doing nothing.

### ISSUE THREAD

**Issue by jtagcat** [waschinski/photo-stream#13]
I went with the 'throw 8 galleries to the wall and see what works' approach. photo-stream is one of them.

Problem:
```
 Configuration file: /photo-stream/_config.yml
             Source: /photo-stream
        Destination: /photo-stream/_site
  Incremental build: disabled. Enable with --incremental
       Generating...
 Configuration file: /photo-stream/_config.yml
```
The container seems halted, doing nothing. Very small CPU and memory usage, no IO usage.

compose:
```
# domain.tld is a redaction, not actual
  domain.tld: # https://github.com/waschinski/photo-stream/
    image: waschinski/photo-stream:latest
    environment:
      - TITLE=domain.tld
      - EMAIL=noreply@domain.tld
      - AUTHOR_NAME=noreply
      - AUTHOR_EMAIL=noreply@domain.tld
      - AUTHOR_WEBSITE=domain.tld
      - DESCRIPTION=domain.tld
      - BASEURL=https://domain.tld/ # also tried with BASEURL=
      - URL=https://domain.tld/
      - SHOW_OFFICIAL_GITHUB=1
    volumes:
      - /path/to/photos:/photo-stream/photos/original:ro
    labels:
      - "traefik.frontend.auth.basic.users=foo:bar"
      - traefik.frontend.rule=Host:domain.tld
      - traefik.port=4000
    networks:
      - proxy
```
