### ISSUE TITLE
All photos regenerated every time container restarts

### ISSUE THREAD

**Issue by lanerussell** [waschinski/photo-stream#88]
Is this behaviour intended? I can understand the site being regenerated, but it seems that all photos are resized into thumbnail, tint, and large every time the container restarts. With my small collection of ~160 photos, this takes nearly 30 minutes, during which time the site is totally down.

I'm running the site in docker-compose, and am using volumes to keep a persistent copy of the site:
```
  photostream:
    image: waschinski/photo-stream:latest
    container_name: photostream
    volumes:
      - /opt/docker/photostream/photos:/photo-stream/photos
      - /opt/docker/photostream/.env:/photo-stream/.env
      - /opt/docker/photostream/config.yml:/photo-stream/_config.yml
      - /opt/docker/photostream/_site:/photo-stream/_site
    restart: always
    ports:
      - 4000:4000
```
